# SPDX-FileCopyrightText: 2025 Chiel Douwes
#
# SPDX-License-Identifier: GPL-3.0-or-later

imports_granularity = "Crate"
newline_style = "Unix"
hard_tabs = true

unstable_features = true
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
