[package]
name = "dbpf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
refpack = "3.0"
modular-bitfield = "0.11.2"
thiserror = "1.0"
enum-iterator = "1.4.0"
texpresso = "2.0.1"
miniz_oxide = { version = "0.7.1", features = ["simd"] }
